version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11

    commands:
      - echo "Installing dependencies..."
      - mvn install
  pre_build:
    commands:
      - echo "Starting pre-build phase..."
      - mvn clean
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 862402797070.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo "Building the application..."
      - mvn clean package
      - echo "Building the Docker image..."
      - docker build -t java-hello-world .
  post_build:
    commands:
      - echo "Tagging the Docker image..."
      - docker tag java-hello-world:latest 862402797070.dkr.ecr.us-east-1.amazonaws.com/java-hello-world:latest
      - docker push 862402797070.dkr.ecr.us-east-1.amazonaws.com/java-hello-world:latest
      - echo "Deployment updated successfully."

artifacts:
  files:
    - target/java-hello-world-1.0-SNAPSHOT.jar
  discard-paths: yes