version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      - echo "Installing dependencies..."
      - mvn install
  pre_build:
    commands:
      - echo "Starting pre-build phase..."
      - mvn clean
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 862402797070.dkr.ecr.us-east-1.amazonaws.com
      - echo "Generating image tag..."
      - TAG="$(date +%Y-%m-%d.%H.%M.%S).$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)"
      - echo "tag is $TAG"
      - sed -i "s/TAG_PLACEHOLDER/$TAG/g" manifest/hello-world-deployment.yml
  build:
    commands:
      - echo "Building the application..."
      - mvn clean package
      - echo "Building the Docker image..."
      - docker build -t java-hello-world:$TAG .
  post_build:
    commands:
      - echo "Tagging the Docker image..."
      - docker tag java-hello-world:$TAG 862402797070.dkr.ecr.us-east-1.amazonaws.com/java-hello-world:$TAG
      - docker push 862402797070.dkr.ecr.us-east-1.amazonaws.com/java-hello-world:$TAG
      - echo "Deployment updated successfully."
      - echo "Preparing deployment artifact..."
      - mkdir -p output
      - cp manifest/hello-world-deployment.yml output/hello-world-deployment.yml

artifacts:
  files:
    - target/zbfs-publisher-0.0.1-SNAPSHOT.jar
    - output/hello-world-deployment.yml
  discard-paths: yes